// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gajqxhqrijnlgtlaljrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhanF4aHFyaWpubGd0bGFsanJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MjA3OTEsImV4cCI6MjA3MTQ5Njc5MX0.TUV0OcTGRVHOBN_8RKhTVHm2iDuSXQJME8ZW9sbAap0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});